Remove index template from backend
build-security/kibana pull request #111
Opened 2022-01-26 10:27 UTC by CohenIdo

2022-01-26 11:43 UTC, kfirpeled commented
Hey @CohenIdo, please reference to the related PR on `integrations` repo

2022-01-26 14:43 UTC, CohenIdo commented
[integrations repo PR](https://github.com/build-security/integrations/pull/3)

2022-01-27 10:20 UTC, kfirpeled approved these changes

2022-01-27 10:21 UTC, kfirpeled commented on x-pack/plugins/cloud_security_posture/common/constants.ts
> +export const CSP_KUBEBEAT_INDEX_PATTERN = 'logs-k8s_cis.result*';
is this change necessary?

2022-02-03 08:29 UTC, ari-aviran requested changes
Lets put this on hold for now until we merge our code to upstream Kibana, we need to have an easy setup, and since we don't have an integration working yet, lets keep it in Kibana server for now

2022-02-22 10:25 UTC, ari-aviran commented
@CohenIdo Please rebase this to solve conflicts and we'll merge this in

2022-02-22 11:08 UTC, ari-aviran approved these changes

2022-02-22 16:17 UTC, merged

2022-02-23 08:37 UTC, orouz commented on x-pack/plugins/cloud_security_posture/server/index_template/findings_mapping.ts
> -export const mapping: MappingTypeMapping = {
FYI the current findings needs this to do search/sort @kfirpeled