bulk create rules on server start
build-security/kibana pull request #115
Opened 2022-01-30 13:31 UTC by orouz

WIP 
----

this PR is mostly a POC of how we could preload json data (`CIS Benchmark` in our case) into a new saved object type we define, so the UI can query it.

done as part of: 
- https://github.com/elastic/security-team/issues/2764

includes:

- [ ] define a `CspRuleSchema` (based on [prior work](https://github.com/elastic/security-team/blob/main/docs/cloud-security-posture-team/Onboarding/Security%20Policies.md)) on plugin `setup`
- [ ] define 2 static rules based on the schema
- [ ] register a new saved object type on plugin `start`:
  - [ ]  define attributes schema (enforced on `create`)
  - [ ]   define migrations 
  - [ ]   define properties mapping for searching / sorting

2022-01-30 13:32 UTC, orouz commented on x-pack/plugins/cloud_security_posture/server/plugin.ts
> +    initializeCspRules(core.savedObjects.createInternalRepository());
example from `x-pack/plugins/canvas/server/plugin.ts:101`

2022-01-30 13:33 UTC, orouz commented on x-pack/plugins/cloud_security_posture/server/saved_objects/benchmark_rules/cis_benchmark_1_4_1_rules.ts
> +export const CIS_BENCHMARK_1_4_1_RULES = [
since this is a temporary solution anyway, i didn't put much thought into where these static rules go.

for now they're at `server/saved_objects/benchmark_rules/cis_benchmark_1_4_1_rules.ts`, which seems sufficient for now

2022-01-30 13:35 UTC, orouz commented on x-pack/plugins/cloud_security_posture/server/saved_objects/benchmark_rules/csp_rule_type.ts
> +  },
i'm not sure if this should be enabled for users or just for debugging.
security rules show their own rules as "rules" in the saved objects ui (under management) 
if we want to show ours too, we need this bit. 

they can delete the rule from that UI (maybe we can't disable it tho)

2022-01-30 13:37 UTC, orouz commented on x-pack/plugins/cloud_security_posture/server/saved_objects/benchmark_rules/csp_rule_type.ts
> +  // migrations: {}
this still needs to be explored. since we don't have any migrations yet and this is a temporary solution anyway, i left it commented out to be there just as a reminder. 

migrations probably deserve their own task when they become relevant. (code coverage for them is encouraged to be 100%)

2022-01-30 13:40 UTC, orouz commented on x-pack/plugins/cloud_security_posture/server/saved_objects/benchmark_rules/initialize_rules.ts
> +  if (existingRules.total !== 0) return;
when we'll have more than 1 benchmark we'll need to re-think how to check what is already loaded. 

this bit borrows from `x-pack/plugins/canvas/server/templates/index.ts`

2022-01-30 14:05 UTC, orouz commented on x-pack/plugins/cloud_security_posture/server/saved_objects/benchmark_rules/csp_rule_type.ts
> +  },
looks like this
![Screen Shot 2022-01-30 at 15 24 51](https://user-images.githubusercontent.com/20814186/151703046-c216402c-25df-4bd9-88cd-a2bf60d34466.png)

2022-01-31 15:42 UTC, eyalkraft commented on x-pack/plugins/cloud_security_posture/common/schemas/csp_rule.ts
> +  rego_code: rt.string(),
Note that `Rego` code will most likely not be included in the rules objects.
see my [comment](https://github.com/elastic/security-team/issues/2451#issuecomment-999629221).

2022-02-03 08:36 UTC, ari-aviran requested changes

2022-02-03 08:36 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/common/schemas/csp_rule.ts
> +// TODO: snake case
What do you mean by this TODO? Consider being more explicit

2022-02-03 08:36 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/common/schemas/csp_rule.ts
> + */
[Please use `//` comments](https://docs.elastic.dev/kibana-dev-docs/contributing/styleguide#use-slashes-for-comments)

2022-02-03 08:36 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/server/saved_objects/benchmark_rules/csp_rule_type.ts
> +        defaultMessage: `CSP Security Rules - ${savedObject.attributes.benchmark.name} ${savedObject.attributes.benchmark.version} ${savedObject.attributes.name}`,
This can not be internationalized, it contains runtime variables, you can consider i18n for the `CSP Security Rules` string only

2022-02-03 10:56 UTC, orouz commented on x-pack/plugins/cloud_security_posture/server/saved_objects/benchmark_rules/csp_rule_type.ts
> +        defaultMessage: `CSP Security Rules - ${savedObject.attributes.benchmark.name} ${savedObject.attributes.benchmark.version} ${savedObject.attributes.name}`,
we set those runtime values - benchmark name and version

similar example: `x-pack/plugins/uptime/server/lib/saved_objects/synthetics_monitor.ts`

can you clarify?

2022-02-03 11:14 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/server/saved_objects/benchmark_rules/csp_rule_type.ts
> +        defaultMessage: `CSP Security Rules - ${savedObject.attributes.benchmark.name} ${savedObject.attributes.benchmark.version} ${savedObject.attributes.name}`,
In the example you linked, they only internationalize the constant part, we can't internationalize the entire string, since the translations are static, it will translate:
`CSP Security Rules - CIS 1.1.4 My Dumb Rule` to `חוק אבטחת ענן` without the dynamic part

2022-02-03 12:14 UTC, orouz commented on x-pack/plugins/cloud_security_posture/server/saved_objects/benchmark_rules/csp_rule_type.ts
> +        defaultMessage: `CSP Security Rules - ${savedObject.attributes.benchmark.name} ${savedObject.attributes.benchmark.version} ${savedObject.attributes.name}`,
i see the difference now. thanks!

2022-02-03 15:59 UTC, orouz commented on x-pack/plugins/cloud_security_posture/common/schemas/csp_rule.ts
> +// TODO: snake case
removed

2022-02-03 15:59 UTC, orouz commented on x-pack/plugins/cloud_security_posture/common/schemas/csp_rule.ts
> + */
fixed

2022-02-03 15:59 UTC, orouz commented on x-pack/plugins/cloud_security_posture/server/saved_objects/benchmark_rules/csp_rule_type.ts
> +        defaultMessage: `CSP Security Rules - ${savedObject.attributes.benchmark.name} ${savedObject.attributes.benchmark.version} ${savedObject.attributes.name}`,
fixed - translation only on our text, not dynamic values. (although they are not really dynamic, we know what they will be, they are not user-generated, so if we really want to we can translate those too later on)

2022-02-06 07:58 UTC, ari-aviran approved these changes

2022-02-06 15:19 UTC, orouz commented on x-pack/plugins/cloud_security_posture/server/saved_objects/cis_1_4_1/rules.ts
> +    id: rule.id,
just a thought - 
we could use 1 rule base schema with `id` same as rule.id
and each integration of same benchmark rules would be a new saved object (for each rule) with generated id and a reference to it's static saved object

2022-02-09 16:42 UTC, kfirpeled commented on x-pack/plugins/cloud_security_posture/common/schemas/csp_rule.ts
> +export const cspRuleAssetSavedObjectType = 'csp_rule_template';
hey, so I think there was a miss understanding.
The template is something that we are still discussing about, and would be developed later on.
The `csp_rule` is actually the rule instance out of the template.
The template contains all the metadata
The rule instance contains the metadata with the rule state

2022-02-09 19:33 UTC, orouz commented on x-pack/plugins/cloud_security_posture/common/schemas/csp_rule.ts
> +export const cspRuleAssetSavedObjectType = 'csp_rule_template';
fixed

2022-02-10 08:37 UTC, ari-aviran approved these changes

2022-02-14 14:43 UTC, merged