Risks panel
build-security/kibana pull request #118
Opened 2022-02-01 17:42 UTC by JordanSh

2022-02-02 21:14 UTC, JordanSh commented on x-pack/plugins/cloud_security_posture/public/pages/compliance_dashboard/compliance_charts/risks_table.test.ts
> +/*
'All Findings Passed' viewing state is being worked on by product/design. will add this state + tests to this file once its available

2022-02-02 21:15 UTC, JordanSh commented on x-pack/plugins/cloud_security_posture/public/pages/compliance_dashboard/compliance_charts/risks_table.tsx
> +}
@orouz 👑

2022-02-02 21:17 UTC, JordanSh commented on x-pack/plugins/cloud_security_posture/public/pages/compliance_dashboard/compliance_charts/risks_table.tsx
> +  );
once i'll add this component to the `integration cards` section of the dashboard, those functions will be passed down. didn't want to get a head of my self for this PR so for now they are inside the component

2022-02-02 21:18 UTC, JordanSh commented on x-pack/plugins/cloud_security_posture/public/pages/compliance_dashboard/dashboard_sections/summary_section.tsx
> +
needed so the number of items in the `Risks Table` won't dictate the height of the entire `summary section` of the dashboard

2022-02-02 21:21 UTC, JordanSh commented on x-pack/plugins/cloud_security_posture/server/routes/stats/stats.ts
> +      totalPassed: passedBucket?.doc_count || 0,
this is kind of sad to do but in case of es won't find an evaluation result it won't return any item. this is the easiest solution I found, there might be something that can be done on a query level but I felt like I wasted too much time on that area. we can come back to that later if it will prove to be a problem.

2022-02-06 08:21 UTC, ari-aviran requested changes
Please mock the relevant data from ES so we could run this with real `kubebeat` data as we discussed verbally. I'll finish the review once this works

2022-02-06 12:16 UTC, JordanSh commented on x-pack/plugins/cloud_security_posture/public/pages/compliance_dashboard/compliance_charts/risks_table.test.ts
> +const mockData: RisksTableProps['data'] = [
tried to export this out to be used as mock data in `RisksTable` but it would cause the page the crash.

2022-02-06 12:17 UTC, JordanSh commented on x-pack/plugins/cloud_security_posture/public/pages/compliance_dashboard/compliance_charts/risks_table.tsx
> +const useMockData: boolean = false;
don't forget to change this setting here to see the mock data. (requested by tehila)

2022-02-06 12:19 UTC, JordanSh commented
all requested changes have been fixed. enable the flag in `RisksTable` to use mock data, don't forget to change `CSP_KUBEBEAT_INDEX_PATTERN`'s value according to what you are working with.

2022-02-07 08:38 UTC, ari-aviran approved these changes

2022-02-07 08:38 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/public/pages/compliance_dashboard/compliance_charts/risks_table.tsx
> +  data: CloudPostureStats['resourceTypesAggs'];
Consider using the type you defined for this `Array<ResourceTypeAgg>`

2022-02-07 08:38 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/public/pages/compliance_dashboard/compliance_charts/risks_table.tsx
> +export const getTop5Risks = (resourceTypesAggs: CloudPostureStats['resourceTypesAggs']) => {
Consider using the type you defined for this `Array<ResourceTypeAgg>`

2022-02-07 08:38 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/public/pages/compliance_dashboard/dashboard_sections/benchmarks_section.tsx
> +                        {/* TODO: no api for this chart yet, using empty state for now. needs BE */}
😆

2022-02-07 08:38 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/public/pages/compliance_dashboard/translations.ts
> +export const RISKS = i18n.translate('xpack.csp.top_5_chart_title', {
I suggest name-spacing this entire file's translations under `xpack.csp.compliance_dashboard` so we won't have collisions with translations from other pages.

Also, this translation needs to change from `top_5_chart_title` to `risks`

2022-02-07 08:38 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/server/routes/stats/stats.ts
> +): Promise<CloudPostureStats['resourceTypesAggs']> => {
Consider using `Array<ResourceTypeAgg>` directly

2022-02-07 08:48 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/pages/compliance_dashboard/compliance_charts/risks_table.tsx
> +  data: CloudPostureStats['resourceTypesAggs'];
i think it's usually better to explicitly define it once and pipe into it in all other cases. 

IMO explicitly re-defining types is ok if the connection isn't all that important. when it is, writing the types hides that connection by making it implicit.

2022-02-07 08:52 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/pages/compliance_dashboard/compliance_charts/risks_table.tsx
> +    [history]
i think `push` would be more likely to be stable between renders than `history` ?

2022-02-07 08:56 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/pages/compliance_dashboard/compliance_charts/risks_table.tsx
> +};
consider making this a function too, even though it has no params.

1 - makes things consistent, like other query getter fns
2 - makes this immutable, which is safer, so arguably suitable for a default query we use

2022-02-07 08:58 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/pages/compliance_dashboard/compliance_charts/risks_table.tsx
> +const maxRisks = 5;
consider taking this as a function param and setting 5 for default value perhaps, instead of a module scope variable.

2022-02-07 09:00 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/pages/compliance_dashboard/compliance_charts/risks_table.tsx
> +export const getTop5Risks = (resourceTypesAggs: CloudPostureStats['resourceTypesAggs']) => {
consider renaming to `getTopRisks` and adding `size: number` or similar as a function param. then calling this fn with `5` for our use case.

2022-02-07 09:38 UTC, orouz commented on x-pack/plugins/cloud_security_posture/server/routes/stats/stats.ts
> +): Promise<CloudPostureStats['resourceTypesAggs']> => {
i think explicitly writing the types actually makes the connection to `CloudPostureStats` implicit. 

sometimes it makes sense (when function is pure and generic) but this one isn't, so to me these types tell the full story: what are the types and where do they come from, as opposed to just what are they.

2022-02-07 09:41 UTC, orouz approved these changes

2022-02-07 12:19 UTC, JordanSh commented on x-pack/plugins/cloud_security_posture/public/pages/compliance_dashboard/dashboard_sections/benchmarks_section.tsx
> +                        {/* TODO: no api for this chart yet, using empty state for now. needs BE */}
🤭

2022-02-07 12:25 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/pages/compliance_dashboard/compliance_charts/risks_table.tsx
> +}
😄 

although, i'm not sure we need to introduce one to kibana, probably using lodash for this

2022-02-07 12:32 UTC, JordanSh commented on x-pack/plugins/cloud_security_posture/public/pages/compliance_dashboard/compliance_charts/risks_table.tsx
> +  data: CloudPostureStats['resourceTypesAggs'];
if I'm going to make this change I would do it across all components that do that, worth a small pr of its own. but in general, I kinda like the way that it works right now.

2022-02-07 12:34 UTC, JordanSh commented on x-pack/plugins/cloud_security_posture/public/pages/compliance_dashboard/translations.ts
> +export const RISKS = i18n.translate('xpack.csp.top_5_chart_title', {
sounds out of scope for this pr.. we can decide on that and make a small pr to change that.

2022-02-07 12:43 UTC, JordanSh commented on x-pack/plugins/cloud_security_posture/public/pages/compliance_dashboard/compliance_charts/risks_table.tsx
> +};
I think those are good points, @ari-aviran preferred it as constant though. I'll change it back for now cause I too think consistency is preferred here.. and also all of those are soon to be deleted after `useFindingsNav` 😜

2022-02-07 12:44 UTC, JordanSh commented on x-pack/plugins/cloud_security_posture/public/pages/compliance_dashboard/compliance_charts/risks_table.tsx
> +const maxRisks = 5;
umm there's really no need in this case. we will never want to display more than 5 here. we actually want to limit it to 5 max only.

2022-02-07 12:44 UTC, JordanSh commented on x-pack/plugins/cloud_security_posture/public/pages/compliance_dashboard/compliance_charts/risks_table.tsx
> +export const getTop5Risks = (resourceTypesAggs: CloudPostureStats['resourceTypesAggs']) => {
as mentioned above, top5 is by choice, we don't want to enable anything above that.

2022-02-07 13:01 UTC, orouz approved these changes

2022-02-07 13:41 UTC, ari-aviran approved these changes

2022-02-07 13:42 UTC, merged