add rules table container
build-security/kibana pull request #121
Opened 2022-02-02 13:29 UTC by orouz

issue:
- https://github.com/elastic/security-team/issues/2765

2022-02-21 13:21 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/common/navigation/constants.ts
> +  rules: { name: 'Rules', path: '/rules', disabled: false },
we need to differentiate between routes and links. `rules` should be included here but not shown on the menubar. this needs to be a new task IMO.

2022-02-22 07:53 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/pages/rules/rules_table_header.tsx
> +          defaultMessage="Showing {totalRulesCount} rules"
TODO: include plural syntax

`x-pack/plugins/security_solution/public/detections/pages/detection_engine/rules/translations.ts`

2022-02-22 08:23 UTC, orouz commented
- [ ] fix toolbar on small screens

![Screen Shot 2022-02-22 at 10 20 23](https://user-images.githubusercontent.com/20814186/155091303-5187137b-441f-4f73-b5d3-e04aa76b7e81.png)

2022-02-24 12:34 UTC, ari-aviran requested changes

2022-02-24 12:34 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/public/pages/rules/rules_table.tsx
> +  const onTableChange = ({ page: _page }: Criteria<RuleSavedObject>) => {
Parameters starting with underscore are usually "ignored" parameters, I suggest calling this `newPage` instead

2022-02-24 12:34 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/public/pages/rules/rules_table.tsx
> +  (value: any, rule: RuleSavedObject) =>
Why not use `boolean` type for `value`?

2022-02-24 12:34 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/public/pages/rules/rules_table_header.tsx
> +          id="xpack.csp.rules.total_rules_count"
Please make sure the formatted message ids in this component match the i18n guidelines

2022-02-24 12:34 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/public/pages/rules/rules_table_header.tsx
> +          defaultMessage="Showing {totalRulesCount} rules"
Please handle singular/plural in all formatted messages in this component (now or in a followup task)

2022-02-24 12:34 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/public/pages/rules/rules_table_header.tsx
> +        <span>&nbsp;&nbsp;|&nbsp;&nbsp;</span>
nit: consider using a margin instead of space characters (it shows the intent more clearly IMO)

2022-02-24 12:34 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/public/pages/rules/rules_table_header.tsx
> +          onChange={(e) => search(e.target.value)}
Please de-bounce this call

2022-02-24 12:34 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/public/pages/rules/rules_table_header.tsx
> +      id={smallContextMenuPopoverId}
Why are you using an `id`?

2022-02-24 12:34 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/public/pages/rules/rules_container.tsx
> +          {...rulesQuery}
Consider passing in the rules and query as explicit props. Benefits IMO are:
1. Readability - explicitly understand what is passed
2. Avoids accidental overrides

2022-02-24 12:34 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/public/pages/rules/rules_container.tsx
> +      {!!hasChanges && (
nit: `hasChanges` is already a boolean

2022-02-24 12:38 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/pages/rules/rules_table_header.tsx
> +      id={smallContextMenuPopoverId}
copy paste from their docs

2022-02-24 12:40 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/pages/rules/rules_container.tsx
> +export type RuleSavedObject = SavedObject<CspRuleSchema>; // SimpleSavedObject
not really. was more of a reminder to myself to ask core about missing properties in `SimpleSavedObject`

i'll remove it

2022-02-24 12:42 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/pages/rules/rules_container.tsx
> +/** Rules with local changes */
i went with /** because it means this text will be available when you hover the variable

i figured it'd be nice to have that info. if the preferred method id // that's ok but they aren't the same

2022-02-24 12:43 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/pages/rules/rules_table.tsx
> +  (value: any, rule: RuleSavedObject) =>
it's from eui types: 
```typescript
 /**
* Describe a custom renderer function for the content
*/
render?: (value: any, record: T) => ReactNode;
```

2022-02-24 12:44 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/pages/rules/rules_table_header.tsx
> +          defaultMessage="Showing {totalRulesCount} rules"
good catch! 

this is handled in a future PR tho

https://github.com/build-security/kibana/pull/140/files#diff-11f2b3aef3d242367641ec0068a8b454a828769aafc9990946fdecd532486bd7R164-R170

2022-02-24 13:21 UTC, JordanSh commented on x-pack/plugins/cloud_security_posture/public/pages/rules/rules_container.tsx
> +          totalRulesCount={localRulesResult.status === 'success' ? localRulesResult.total : 0}
so if we have an error we want to display 0? sounds a bit misleading in this case unless I understand something incorrectly.
in what cases do we get error status? maybe we want to display it instead in some way? if we only display this count in case `status === success` we can also just say `localRulesResult.status === 'success' && localRulesResult.total`

2022-02-24 13:46 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/pages/rules/rules_container.tsx
> +          totalRulesCount={localRulesResult.status === 'success' ? localRulesResult.total : 0}
1 - showing 0 when there is no rules seems OK as we're not lying.. we have 0 rules to work with.
2 - you can't pass `&&` because it may return false, not a number

2022-02-24 14:31 UTC, JordanSh commented on x-pack/plugins/cloud_security_posture/public/pages/rules/rules_container.tsx
> +          {...rulesQuery}
I agree with Ari, in most cases I'm ok with the method of prop passing but here its kinda hard to understand what is the table data since we have `data, baseData, localRulesResult, getLocalRulesResult` all passing the data around.. explicit props would add readability here

2022-02-24 14:33 UTC, JordanSh commented on x-pack/plugins/cloud_security_posture/public/pages/rules/rules_table.tsx
> +// import moment from 'moment';
remove

2022-02-24 14:34 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/pages/rules/rules_container.tsx
> +type DistributivePick<T, K extends keyof T> = T extends unknown ? Pick<T, K> : never;
i was trying to hide it 😆 

but actually, i removed it in the next PR. 

eventually i came to realize piping the request's tagged template union type is nice, but it'd be better if we just provided a [simpler interface](https://github.com/build-security/kibana/pull/140/commits/517d1e877cc78a0323f4acc54960793d057f3632#diff-44f209bcb4b152498fa7983b9f278a1caedbe58dad762a5c0874653fdb2451bdR23-R30)

2022-02-24 14:49 UTC, JordanSh commented on x-pack/plugins/cloud_security_posture/public/pages/rules/rules_table.tsx
> +    field: 'section', // TODO: what field is this?
rule.section

2022-02-24 14:59 UTC, JordanSh commented on x-pack/plugins/cloud_security_posture/public/pages/rules/rules_table.tsx
> +    render: createRuleEnabledSwitchRenderer({ toggleRule }),
```suggestion
    render: (value: any, rule: RuleSavedObject) => 
    <EuiSwitch
        label=""
        checked={value}
        onChange={() => toggleRule(rule)}
        data-test-subj={TEST_SUBJECTS.getCspRulesTableItemSwitchTestId(rule.attributes.id)}
      />
```

nit: i think this is clearer.. i would treat `ruleNameRenderer` the same.. makes the `getColumns` function easier to visualize only by reading

2022-02-24 15:00 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/pages/rules/rules_table.tsx
> +    render: createRuleEnabledSwitchRenderer({ toggleRule }),
to me this suggestion is less clear, as it breaks the rest of the columns structure. each one takes a renderer function, so having just 1 of them do smth else feels wrong and inconsistent.

2022-02-24 15:14 UTC, JordanSh commented on x-pack/plugins/cloud_security_posture/public/pages/rules/rules_table_header.tsx
> +        <span>&nbsp;&nbsp;|&nbsp;&nbsp;</span>
using text char to draw the separting element is probably not the optimal solution here, I would just use a vertical rule or `borderLeft: 1px` with some margin between the components

2022-02-24 15:21 UTC, JordanSh commented on x-pack/plugins/cloud_security_posture/public/pages/rules/rules_table_header.tsx
> +  const data = items.map((item) => (
needs a better name

2022-02-24 15:27 UTC, JordanSh commented on x-pack/plugins/cloud_security_posture/public/pages/rules/rules_table_header.tsx
> +  const closePopover = () => setPopover(false);
ocd: imo most of the time one-liners don't need space between them (this is lintable btw, have space only between multilines). space between one liners is good when the context is different for example:

```
const a = 1
const b = 2
const c = a + b

const d = e.map(i => i.f)
```
(shameful comment honestly)

2022-02-24 15:28 UTC, JordanSh commented on x-pack/plugins/cloud_security_posture/public/pages/rules/rules_table_header.tsx
> +  const button = (
consider naming `selectAllButton`

2022-02-24 15:29 UTC, JordanSh commented on x-pack/plugins/cloud_security_posture/public/pages/rules/test_subjects.ts
> +export const CSP_RULES_TABLE_REFRESH_BUTTON = 'csp_rules_table_refresh_button';
```
const CSP_RULES_TEST_SUBJECTS: {
 CONTAINER: ...
}
```

2022-02-24 15:45 UTC, JordanSh commented
is this eui bug?

https://user-images.githubusercontent.com/51442161/155557801-ccbc6abe-36e8-4c51-8243-3a54efa9e028.mp4

2022-02-28 11:05 UTC, JordanSh commented on x-pack/plugins/cloud_security_posture/public/pages/rules/rules_table.tsx
> +    render: createRuleEnabledSwitchRenderer({ toggleRule }),
```
const getColumns = ({
  toggleRule,
}: GetColumnProps): Array<EuiTableFieldDataColumnType<RuleSavedObject>> => [
  {
    field: 'attributes.name',
    name: TEXT.RULE_NAME,
    width: '60%',
    truncateText: true,
    render: (name: string) => (
      <EuiLink className="eui-textTruncate" title={name}>
        {name}
      </EuiLink>
    ),
  },
  {
    field: 'section', // TODO: what field is this?
    name: TEXT.SECTION,
    width: '15%',
  },
  {
    // TODO: get timestamp value
    // add SavedObject["updated_at"] to SimpleSavedObject?
    field: 'updated_at',
    width: '15%',
    name: TEXT.UPDATED_AT,
    render: (timestamp: string) => moment.duration(moment().diff(timestamp)).humanize(),
  },
  {
    field: 'attributes.enabled',
    name: TEXT.ENABLED,
    width: '10%',
    render: (value: any, rule: RuleSavedObject) => (
      <EuiSwitch
        label=""
        checked={value}
        onChange={() => toggleRule(rule)}
        data-test-subj={TEST_SUBJECTS.getCspRulesTableItemSwitchTestId(rule.attributes.id)}
      />
    ),
  },
];
```

of course, I meant that this should be done to all columns. just by looking at the example above, I can visualize this in my head already. no need to jump between 3 functions and no curry function.

still of course if you dont like it don't do it. just wanted to be clear that I indeed meant this treatment for all the columns

2022-03-10 10:31 UTC, closed without merging