Cases panel coming soon state
build-security/kibana pull request #122
Opened 2022-02-06 15:16 UTC by JordanSh

## Summary
solves:
- https://github.com/elastic/security-team/issues/2759

needs to be merged after:
- https://github.com/build-security/kibana/pull/118

## UI
<img src="https://user-images.githubusercontent.com/51442161/152687608-fbdbdfdc-a752-405c-9576-207d8a73f3f4.png" width=500>

2022-02-06 15:21 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/common/utils/getFormattedNum.ts
> +export const getFormattedNum = (num: number) =>
1. cool !
2. filename should be `snake_case`

2022-02-06 15:22 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/components/chart_panel.tsx
> +      <EuiFlexGroup direction="column" gutterSize="none" style={{ height: '100%' }}>
do we need the `height` addition here?

2022-02-06 15:24 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/pages/compliance_dashboard/compliance_charts/risks_table.tsx
> +    [history]
not sure if `history` is stable
i _think_ `push` is tho

2022-02-07 08:46 UTC, ari-aviran commented
> # TO BE REVIEWED AFTER #118 IS MERGED

This is easily missed, please don't assign reviewers until a PR is ready for review :)

2022-02-07 08:46 UTC, ari-aviran requested changes
Please re-request a review after #118 is merged

2022-02-07 13:40 UTC, JordanSh commented
> > # TO BE REVIEWED AFTER #118 IS MERGED
> 
> This is easily missed, please don't assign reviewers until a PR is ready for review :)

of course. not opening as draft was a miss click

2022-02-08 11:39 UTC, ari-aviran commented
@JordanSh please rebase this over `main` (you can use the cherry-picking method @orouz suggested)

2022-02-08 18:42 UTC, closed without merging