first commit
build-security/kibana pull request #133
Opened 2022-02-15 08:43 UTC by CohenIdo

2022-02-15 15:56 UTC, CohenIdo commented on x-pack/plugins/cloud_security_posture/server/routes/benchmarks/benchmarks.test.ts
>      describe('test getPackagePolicies', () => {
the test removed because `getPackagePolicies` cannot get `agentPolicyService` as undefined anymore.

2022-02-15 16:02 UTC, CohenIdo commented on x-pack/plugins/cloud_security_posture/server/routes/configuration/update_rules_configuration.ts
> +import { getPackagePolicies } from '../benchmarks/benchmarks';
@kfirpeled, Do you think the function that is used by both - `benchmarks` and `update_rules_configuration` should locate in another place?

2022-02-16 10:44 UTC, kfirpeled requested changes
when tested locally I got the following error:
`Failed to update rules configuration on package policy Package policy is invalid: vars.dataYaml: dataYaml var definition does not exist`

Looks like the integration is required to define the var we use here

also lets change the api to work with a specific package policy id. (benchmark instance). and add validations and errors for that as well (like 404 not found or 400 bad request)

2022-02-28 11:59 UTC, kfirpeled commented
Some stuff to fix

```
    "statusCode": 500,
    "error": "Internal Server Error",
    "message": "package policy Id  is not exist"
```

if not found status code should be 404
wrap the actual value with `'`

2022-02-28 13:49 UTC, kfirpeled requested changes
the api is fetching all rules regardless of the integration id
also - missing tests to cover that use case

please fix

2022-02-28 13:49 UTC, kfirpeled commented on x-pack/plugins/cloud_security_posture/server/routes/benchmarks/benchmarks.ts
> +        if (!agentPolicyService || !agentService || !packagePolicyService) {
we need to be aware that comments about internal tickets should not go public

2022-02-28 13:49 UTC, kfirpeled commented on x-pack/plugins/cloud_security_posture/server/routes/configuration/update_rules_configuration.ts
> +    // TODO: improve this validator to support any future CSP package
open ticket in the backlog

2022-02-28 13:49 UTC, kfirpeled commented on x-pack/plugins/cloud_security_posture/server/routes/configuration/update_rules_configuration.ts
> +        // TODO: This validate can be remove after #2819 will be merged
same with this comment

2022-02-28 13:49 UTC, kfirpeled commented on x-pack/plugins/cloud_security_posture/server/routes/configuration/update_rules_configuration.ts
> +  const cspRules = await soClient.find<CspRuleSchema>({
this should be filtered by the policy package - currently it is fetching all rules from all benchmarks which will cause issues when having more than one policy

2022-02-28 13:59 UTC, kfirpeled commented on x-pack/plugins/cloud_security_posture/server/routes/configuration/update_rules_configuration.ts
> +  const cspRules = await soClient.find<CspRuleSchema>({
I realized we need to do that only after uri would finish his integration part
so lets open a ticket for that in that epic?

2022-03-01 16:10 UTC, CohenIdo commented on x-pack/plugins/cloud_security_posture/server/routes/benchmarks/benchmarks.ts
> +        if (!agentPolicyService || !agentService || !packagePolicyService) {
- https://github.com/elastic/security-team/issues/2888#issuecomment-1055600533

2022-03-01 16:13 UTC, CohenIdo commented
> Member

The way that we throw error today (`throw new Error(`package policy Id ${packagePolicyId} is not exist`);` does not enables to edit the error code. I need to investigate what is the proper way to throw errors in cases like this

2023-04-12 14:14 UTC, closed without merging