Data types3
build-security/kibana pull request #27
Opened 2021-11-30 14:17 UTC by CohenIdo

2021-11-30 14:20 UTC, orouz commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
> +const getFindingsEsQuery = (benchmark: string = '*', cycleId: string): CountRequest => {
TS has [type inference](https://www.typescriptlang.org/docs/handbook/type-inference.html)

so we whenever we assign a value to a variable, that type of that variable will be inferred from the value

so we don't need to say `benchmark: string = '*'` because it's already inferred to be a string

2021-11-30 14:20 UTC, orouz commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
> +const getPassFindingsEsQuery = (benchmark: string = '*', cycleId: string): CountRequest => {
same comment as before - no need for `string` in `benchmark`

2021-11-30 14:21 UTC, orouz commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
> +          { term: { 'run_id.keyword': cycleId } },
out of curiosity - do we need to pass `cycleId` *twice* in `run_id.keyword` ?

2021-11-30 14:22 UTC, orouz commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
> +  sort: { '@timestamp': 'desc' }, // todo - fix error
either fix the error or add a more descriptive comment?

2021-11-30 14:28 UTC, orouz commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
> +          totalFailed: allFindingsStats.totalFailed,
```suggestion
  ...allFindingsStats,
```

since all the keys in `allFindingsStats` are re-assigned in `body`, we can use [spread](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax)

2021-11-30 14:37 UTC, CohenIdo commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
> +  sort: { '@timestamp': 'desc' }, // todo - fix error
done

2021-11-30 14:37 UTC, orouz commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
> +        const evaluationsPerFilename = await getEvaluationPerFilename(esClient, latestCycleID);
it seems none of the request depend on the result of the previous one, and we need all 3 to actually return something meaningful, so we might as well consider them a transcation

in which case - 

```typescript
const [allFindingsStats,allFindingsStats,allFindingsStats] = await Promise.all([
getAllFindingsStats(esClient, latestCycleID),
getScorePerBenchmark(esClient, latestCycleID),,
getEvaluationPerFilename(esClient, latestCycleID)])
```

2021-11-30 14:37 UTC, CohenIdo commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
> +          { term: { 'run_id.keyword': cycleId } },
don't sure that I understand

2021-11-30 14:37 UTC, orouz commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
> +// });
can we remove this?

2021-11-30 14:37 UTC, CohenIdo commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
> +const getPassFindingsEsQuery = (benchmark: string = '*', cycleId: string): CountRequest => {
done

2021-11-30 14:37 UTC, CohenIdo commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
> +const getFindingsEsQuery = (benchmark: string = '*', cycleId: string): CountRequest => {
done

2021-11-30 14:37 UTC, orouz commented on x-pack/plugins/security_solution/server/cloud_posture/types.ts
> +  postureScore?: string | undefined;
IMO - `score` is usually a number, not a string

2021-11-30 14:38 UTC, CohenIdo commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
> +        }
done

2021-11-30 14:40 UTC, CohenIdo commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
> +// });
no, I want to use it - need to make it work

2021-11-30 14:51 UTC, CohenIdo commented on x-pack/plugins/security_solution/server/cloud_posture/types.ts
> +  postureScore?: string | undefined;
Yep

2021-11-30 15:04 UTC, CohenIdo commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
> +        const evaluationsPerFilename = await getEvaluationPerFilename(esClient, latestCycleID);
done

2021-11-30 15:07 UTC, CohenIdo commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
> +          totalFailed: allFindingsStats.totalFailed,
done

2021-11-30 15:07 UTC, orouz commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
> +          throw 'cycle id is missing';
```throw Error(...)```

2021-11-30 15:08 UTC, CohenIdo commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
> +        }
done

2021-11-30 15:12 UTC, orouz commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
>          name: benchmark,
maybe the key should be `name` or `benchmark`, no real need to have intermediate vars

2021-11-30 15:13 UTC, orouz commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
> +  //@ts-expect-error
usually it's better to add the TS error number as we don't want to ignore other errors

2021-11-30 15:14 UTC, orouz commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
> +  return latestCycleId;
_nit_

1. change `run_id` to `cycle_id` so we don't have multiple names for the same thing
2. just return `lastCycle._source?.run_id`

2021-11-30 15:17 UTC, orouz commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
> +          filter: [{ term: { 'run_id.keyword': cycleId } }],
it seems the only difference between passing a benchmark string or not is that we add this line:
```
{ term: { 'rule.benchmark.keyword': benchmark } },
```

so i _think_ the entire query can be the same (no need for the `if (..)`) and we'd just pass `*` where `benchmark` is passing and it should work the same, i think

2021-11-30 15:19 UTC, orouz commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
> +const getFindingsEsQuery = (benchmark: string = '*', cycleId: string): CountRequest => {
```suggestion
const getFindingsEsQuery = (cycleId: string, benchmark = '*', ): CountRequest => {
```

note that currently we have `*` as default `benchmark` value but still we're calling this function with `*` because the of the arguments order.

if we move `benchmark` to be the last param, we can actually benefit from the default param

2021-11-30 15:20 UTC, orouz commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
>      totalFailed: filenameObject.group_docs.buckets.find((e) => e.key === 'failed')?.doc_count || 0,
this reads a bit weird. 

if we have `buckets`, running `find` will return the first match
shouldn't we do:
`filenameObject.group_docs.buckets.filter((e) => e.key === 'passed').length` ?

2021-11-30 15:21 UTC, orouz commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
>    // @ts-ignore
why is // @ts-ignore here?

2021-11-30 15:22 UTC, orouz requested changes
see comments

2021-11-30 15:30 UTC, orouz commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
>      totalFailed: filenameObject.group_docs.buckets.find((e) => e.key === 'failed')?.doc_count || 0,
also - shouldn't `key` be named `evaluation.result` ?

2021-11-30 15:33 UTC, orouz commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
> +// });
IMO it's better to not have commented out code in source files

you can keep it elsewhere without affecting the main branch.. 

imagine if everybody kept their snippets in source code.. it'd be pretty messy

2021-11-30 15:35 UTC, orouz commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
> +          { term: { 'run_id.keyword': cycleId } },
yeah i didn't read it properly - 
but in anyway - `getPassFindingsEsQuery` sends 2 queries depending on its arguments, and it can be combined to just one.

2021-11-30 15:38 UTC, orouz commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
> +const roundScore = (value: number) => (value * 100).toFixed(1);
maybe add a comment mentioning `value` is going to be a number between `0-1`

2021-11-30 15:40 UTC, orouz commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
>    size: 1000,
not sure what we should do regarding the `size` 

using `1000` works fine for now, but i'm guessing we'll need to think about this.

2021-11-30 15:41 UTC, orouz commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
> +}
i think it'd be better if we didn't switch between `run_id`/`cycle_id` and used one of them all the way

2021-11-30 15:42 UTC, orouz commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
> +  const lastCycle = latestFinding.body.hits.hits[0];
`lastCycle` may be `undefined` if `hits` is empty so we need to add a check here otherwise it may throw

2021-11-30 15:45 UTC, orouz commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
> +const getScorePerBenchmark = async (
the name of the function hints that we're going to take a `benchmark` array, but we're not (i see it's hard-coded, probably better to pass it)

2021-11-30 15:52 UTC, CohenIdo commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
> +}
waiting for update in agent

2021-11-30 15:53 UTC, orouz commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
> +        postureScore: roundScore(benchmarkPassFindings.body.count / benchmarkFindings.body.count),
if `benchmarkFindings.body.count` is `0` we're going to get `NaN`

2021-11-30 15:54 UTC, orouz commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
>  /* eslint-disable  */
remove this

2021-11-30 15:54 UTC, CohenIdo commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
> +        postureScore: roundScore(benchmarkPassFindings.body.count / benchmarkFindings.body.count),
that's what we talked earlier - and Yarden said the FE should handle it

2021-11-30 15:57 UTC, CohenIdo commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
> +const getScorePerBenchmark = async (
there is a comment `//todo: get benchmarks from DB` and also the query function was implemented (`getBenchmarksQuery`) for some reason don't work right now and is also in the todo list

2021-11-30 15:58 UTC, CohenIdo commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
> +  const lastCycle = latestFinding.body.hits.hits[0];
it is checked in line 179 (`if (latestCycleID === undefined) `)

2021-11-30 15:59 UTC, CohenIdo commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
>    size: 1000,
sure, we need to research this topic

2021-11-30 16:27 UTC, orouz commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
> +  const lastCycle = latestFinding.body.hits.hits[0];
`lastCycle?._source?.run_id;`

2021-11-30 16:27 UTC, orouz commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
> +  const lastCycle = latestFinding.body.hits.hits[0];
note the added `?`

2021-12-01 15:53 UTC, orouz commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
> +  if (benchmark !== undefined) {
`if (benchmark) { ... }`

2021-12-01 15:53 UTC, orouz commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
> +  if (evaluationResult !== undefined) {
same ^

2021-12-01 15:54 UTC, orouz commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
> +    // totalPassed: 0,
we should remove commented out code

2021-12-01 15:54 UTC, orouz commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
> +  group_docs: AggregationsTermsAggregate<DictionaryResponseBase<string, number>>;
why `number` ?

2021-12-01 16:02 UTC, orouz commented on x-pack/plugins/security_solution/server/cloud_posture/types.ts
> +  totalFailed: number | undefined;
i think it's better if `totalPassed` and `totalFailed` would be optional, like `totalFindings`, instead of `undefined`

keep it consistent

2021-12-01 16:03 UTC, orouz commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
> +    totalFailed: filenameObject.group_docs.buckets.find((e) => e.key === 'failed')?.doc_count || 0,
i don't think we should add `|| 0` here 

if there is not result from `filenameObject`, then these properties should be `undefined`, as per the interface 

passing on `0` can be misleading

2021-12-01 16:05 UTC, orouz commented on x-pack/plugins/security_solution/server/cloud_posture/routes/score.ts
>    const counterPerFilename = evaluationsBuckets.buckets.map((filenameObject) => ({
_nit_

`buckets.map(bucket => ...)` 

not an issue! just _my_ preferences, maybe you like it too :P

2021-12-01 17:12 UTC, orouz approved these changes

2021-12-02 15:50 UTC, merged