Csp shared root
build-security/kibana pull request #43
Opened 2021-12-09 10:06 UTC by orouz

demo from #19 

but with our code as a root plugin

and a subplugin in security solution to redirect to our app

2021-12-21 21:11 UTC, orouz commented
rebased, fixed conflicts and some ts errors. had to drop a commit i accidentally [introduced](https://github.com/elastic/kibana/commit/4a5410e2860858dd276772e5ae45b91ee007afc2)

this _should_ be working.

(can't tell as i'm having issues with data now, so i'll verify later.)

2021-12-21 21:14 UTC, orouz commented on x-pack/plugins/security_solution/public/app/home/template_wrapper/index.tsx
> +    const loc = useLocation();
remove

2021-12-21 21:15 UTC, orouz commented on x-pack/plugins/security_solution/public/cloud_posture/routes.tsx
> +  React.useEffect(() => {
use `<Redirect>` with `getAppUrl`

2021-12-21 21:15 UTC, orouz commented on x-pack/plugins/security_solution/public/common/components/navigation/use_security_solution_navigation/index.tsx
> +export const useSecuritySolutionNavigation = (navTabs: any = navTabsOriginal) => {
fix types

2021-12-23 15:21 UTC, ari-aviran requested changes
FE only review. I'll soon edit every comment with a linked ticket so we can actually track these comments.

General comments:
1. We need to add our team to the `.github/CODEOWNERS` file
2. `x-pack/plugins/cloud_security_posture/public/components/testing_chart.tsx` is empty - please remove it

2021-12-23 15:21 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/public/pages/findings/utils.tsx
> +  const getKubebeatDataView = () => findDataView().then((v) => (v ? v : createDataView()));
I believe we should have error handling here

2021-12-23 15:21 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/public/pages/findings/utils.tsx
> +  return useQuery(['kubebeat_dataview'], getKubebeatDataView);
Consider extracting the query name to a constant

2021-12-23 15:21 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/public/pages/findings/utils.tsx
> + *  registers a kibana data view for kubebeat* index
This also runs a query for the data view, no?

2021-12-23 15:21 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/public/pages/findings/utils.tsx
> + *  Temp DataView Utility
Not temp :)

2021-12-23 15:21 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/public/pages/findings/utils.tsx
> +  const createDataView = () =>
We should probably create this elsewhere and not in runtime when we run the first query

2021-12-23 15:21 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/public/pages/findings/utils.tsx
> +      console.error('Unable to encode source');
Do it please

2021-12-23 15:21 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/public/pages/findings/utils.tsx
> +      const next = `source=${encode(v)}`;
Lets extract `source` into a constant and re-use it later here

2021-12-23 15:21 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/public/pages/findings/utils.tsx
> + * Temp URL state utility
Not temp :)

2021-12-23 15:21 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/public/pages/findings/utils.tsx
> +      console.error('Unable to decode URL');
Do it please

2021-12-23 15:21 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/public/pages/findings/utils.tsx
> + */
Lets do this, I'll open a task

2021-12-23 15:21 UTC, ari-aviran requested changes
FE only review. I'll soon edit every comment with a linked ticket so we can actually track these comments.

General comments:
1. We need to add our team to the `.github/CODEOWNERS` file
2. `x-pack/plugins/cloud_security_posture/public/components/testing_chart.tsx` is empty - please remove it

2021-12-23 15:40 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/components/chart_panel.test.tsx
> +const TestingChart = ({ data }: { data: string }) => {
i _think_ the only benefit of using `React.FC<{prop: string>` is it includes types for `children` in your props.

otherwise using an interface to type the Props is preferable IMO as it's just less code and the return type of JSX is implied anyway.

2021-12-23 15:52 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/common/types.ts
> + */
it's used because we don't want UI components to know anything about `UseMutationResult` which is a 3rd library api we use for fetching, which also has many other unrelated props relevant only for fetching.

all the UI components need to know is `data | error | status`, which we can get for free from our mutation result. 
usually we'd just use `Pick` but it will lose the tagged union info so we won't get a union type back. 

we can replace it with, pretty much the same
https://github.com/build-security/kibana/blob/1035da7e53ed558401ff757180a1563f9643f6ad/x-pack/plugins/security_solution/public/cloud_posture/pages/findings/types.ts#L8-L12

or just add manual types for each props that needs it, like `isLoading`

it is usually better to avoid tricky types

2021-12-23 15:59 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/components/chart_panel.tsx
> +export const ChartPanel = ({
can you please elaborate on why that is? 🧐.

2021-12-23 17:04 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/public/common/types.ts
> + */
@orouz Thanks for clarifying. Which option do you prefer, keeping the complex type or manually specifying a union type?

I somewhat prefer manually specifying a union type as it is much more readable and understandable what's actually on that type, but I leave it up to you

2021-12-23 17:12 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/common/types.ts
> + */
i'll go with the simpler approach for now as we only have 1 consumer, it's probably premature anwyay. 

if this gets to be be a collective issue later on we can always add it

2021-12-23 17:21 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/components/page_template.tsx
> +      <NavLink to={route.path as string} activeStyle={activeItemStyle}>
we can fix this by defining our routes with a narrowed down version of  `RouteProps` from `react-router` and make the `path` prop only a `string` (and not `string[]` too)

2021-12-23 17:22 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/components/page_template.tsx
> +    <KibanaPageTemplate {...defaultProps} {...props}>
i think so? 
they are applied first so the component works with a default param but if users provided something then it overrides it.

2021-12-23 17:23 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/components/section_container.tsx
> +  children: React.ReactNode;
this is a good use case for a component with `React.FC`

2021-12-23 17:28 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/pages/compliance_dashboard/compliance_charts/compliance_stats.tsx
> +  const stats = [
can you clarify? not sure i follow

2021-12-23 17:33 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/pages/findings/findings.test.tsx
> +const spy = jest.spyOn(utils, 'useKubebeatDataView');
i tried the partial mock but that didn't work for dynamic mocking, as i need it to return different values for each test, 

i'll try again though, anyway this test is also much slower than other ones, so it definitely needs to be iterated

2021-12-23 17:39 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/plugin.ts
> +      id: 'csp_root',
we used `csp` in `security_solution` and this was added when we still had code there 

should be renamed

2021-12-23 17:44 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/pages/findings/findings_container.tsx
> +    mutation.mutate(void 0, {
yeah `void 0` is weird, definitely need to change this. `undefined` won't work though, this isn't about runtime values, it's about types only.

`mutation.mutate` is how we trigger the mutation function we defined, an in general we can provide arguments for it but in this case we don't take any arguments so it gets defined as `void`

2021-12-23 17:52 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/pages/findings/findings_flyout.tsx
> +type FindingsTab = typeof tabs[number];
personally i usually prefer not using `Enums` in TS and find literals to be nicer to work with.

i can't find it now, but IIRC - `enums` and `namespaces` are legacy TS features

also note i can already iterate on the values, as `tabs` is an array
which we can easily derive a union type of its members (as it's a tuple)

2021-12-23 17:59 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/pages/findings/findings_flyout.tsx
> +  listItems: Array<[EuiListItemsProps['title'], EuiListItemsProps['description']]>;
yeah, much ceremony going on here

was meant to link the types of `Card` with the types of `EuiListItemsProps` as the former is just a pipe. 

probably too much

2021-12-27 08:12 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/public/plugin.ts
> +      id: 'csp_root',
So lets rename :)

2021-12-27 08:25 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/public/pages/findings/findings_container.tsx
> +    mutation.mutate(void 0, {
Passing `undefined` should work, [`undefined` is assignable to `void` type](https://www.typescriptlang.org/docs/handbook/type-compatibility.html#any-unknown-object-void-undefined-null-and-never-assignability). In general the expression `void 0` is equivalent to `undefined`, [see this for more info](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/void)

2021-12-27 08:27 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/public/components/page_template.tsx
> +      <NavLink to={route.path as string} activeStyle={activeItemStyle}>
`route.path` is already typed solely as `string`, this assertion does nothing
![image](https://user-images.githubusercontent.com/94899776/147451853-6fc82ea5-55fc-49e7-90b1-ac48cf6f3060.png)

2021-12-27 08:33 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/public/pages/compliance_dashboard/compliance_charts/compliance_stats.tsx
> +  const stats = [
Instead of defining the "stats" details in an array, we can define a component that takes these properties as props, and then directly render these stats with JSX using that component

2021-12-27 08:56 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/components/page_template.tsx
> +      <NavLink to={route.path as string} activeStyle={activeItemStyle}>
right, it was changed. these are `navigationLinks` not `routes.`

2021-12-27 09:21 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/pages/compliance_dashboard/compliance_charts/compliance_stats.tsx
> +  const stats = [
still not sure i follow. how will a component replace an array? can you give an example how that looks?  

to me it seems using an array to iterate on a bunch of items is the natural choice.

2021-12-27 10:17 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/pages/findings/findings_container.tsx
> +    mutation.mutate(void 0, {
it does work! nice 👌 

kinda surprising though, as `void` and `undefined` [are not the same](https://stackoverflow.com/a/58885486)  from a type perspective, even if `void` evaluates to `undefined`

in return types, where returning `undefined`, it is a value to be used and returning `void` is a no-value not to be used. i thought it works the same for arguments... guess not!

2021-12-27 11:22 UTC, JordanSh commented on x-pack/plugins/cloud_security_posture/common/types.ts
> +  totalFailed?: number;
I've talked about that with Ido a few days ago, apparently, it's because they can be missing from the request but IMO in case they are missing the call should just return an error that we can display to the user.
In case of missing data or error, I don't think we should return a 0 either way.
0 should be saved to when the result is actually 0.
@CohenIdo what's your opinion here?

2021-12-27 11:29 UTC, JordanSh commented on x-pack/plugins/cloud_security_posture/common/types.ts
> +  postureScore?: Score;
Not all findings are failures, findings are just rules that were found on a policy, a 'hit' if you may call it that.
The posture score will be some kind of aggregation between the severity level and the amount of FAILED findings to PASSED findings. The actual algorithm is to be determined.
So 0 findings basically mean `no data` which will probably be represented with some empty state.

2021-12-27 11:35 UTC, JordanSh commented on x-pack/plugins/cloud_security_posture/common/types.ts
> +export interface CloudPostureStats extends BenchmarkStats {
The name is not necessary, will change

2021-12-27 11:36 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/pages/findings/utils.tsx
> +      const next = `source=${encode(v)}`;
i would prefer not sharing the `source` constant via `import/export` and instead provide only this hook
which comes with a a `setSource` and `source` which is the current one 

i prefer this because the hook it meant to provide observable query params and it does. the `source` param is an implementation detail and if it were to be exported as is, every consumer would have to juggle other stuff like `encode` and they really shouldn't IMO.

2021-12-27 11:45 UTC, orouz commented on x-pack/plugins/cloud_security_posture/common/types.ts
> +  totalFailed?: number;
i also think `0` is a value and should be used when it is calculated. not when as a default for some edge case.

2021-12-27 11:54 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/components/chart_panel.tsx
> +  <EuiFlexGroup justifyContent="center" alignItems="center" data-test-subj="loading">
_Tip_

eui has a [page](https://elastic.github.io/eui/#/display/empty-prompt) on `EmptyPrompt` with examples for `loading` and `error`, might be useful here

2021-12-27 12:00 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/pages/compliance_dashboard/dashboard_sections/benchmarks_section.tsx
> +                    title: 'Compliance Score',
looks like `i18n` is tracked along other tasks. 
i think it might be a good idea to separate it:
1. infra 
2. actual texts - sweep on all code

2021-12-27 12:02 UTC, JordanSh commented on x-pack/plugins/cloud_security_posture/public/components/section_container.tsx
> +      buttonContentClassName="accordion-button"
this component was copy-pasted from another solution a while ago. I'll remove the file since its no longer used

2021-12-27 12:07 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/pages/findings/findings.test.tsx
> +    spy.mockImplementation(() => ({ status: 'success', data: undefined } as any));
this is interesting. it works! 

but `UseQueryResult` has only `{ status: 'success', data: TData}` where `TData = unknown` 

and yet it's OK to cast while missing the `data` property. 

this doesn't work, for example:
```typescript
type A = { type: 'a'; data: 1 };
type B = { type: 'b'; data: 2 };
type Foo = A | B;

const foo = { type: 'a ' } as Foo; // can't cast with missing `data
```

don't know why yet, but definitely interesting !

2021-12-28 07:19 UTC, ari-aviran requested changes

2021-12-28 07:19 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/server/routes/stats/stats.ts
> +  const queryReult = await esClient.search(getBenchmarksQuery());
Missing an `s` in `queryResult`

2021-12-28 07:19 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/server/routes/stats/stats.ts
> +  const bencmarksBuckets = queryReult.body.aggregations?.benchmarks as AggregationsTermsAggregate<
Missing an `h` in `benchmarkBuckets`

2021-12-28 07:19 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/server/routes/stats/stats.ts
> +  const failedFindings = await esClient.count(getFindingsEsQuery(cycleId, RULE_FAILED));
Running these 3 queries synchronously seems inefficient - consider looking for alternatives with a single query (or without awaiting every result)

2021-12-28 07:19 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/server/routes/stats/stats.ts
> +  const benchmarkScores = Promise.all(ps);
What you have in `ps` is not promises but just objects. Every promise in this flow has been resolved already since you `await` on all the async calls. If you want this flow to be async and not wait between `esClient.count` calls you'll have to refactor this method - it should not `await` for every async call, here is something I threw together, but not sure if it works properly so please test:

```typescript
export const getBenchmarksStats = async (
  esClient: ElasticsearchClient,
  cycleId: string,
  benchmarks: string[]
): Promise<BenchmarkStats[]> => {
  const benchmarkPromises = benchmarks.map((benchmark) => {
    const benchmarkFindings = esClient.count(getFindingsEsQuery(benchmark, cycleId));
    const benchmarkPassedFindings = esClient.count(
      getFindingsEsQuery(cycleId, RULE_PASSED, benchmark)
    );
    const benchmarkFailedFindings = esClient.count(
      getFindingsEsQuery(cycleId, RULE_FAILED, benchmark)
    );

    return Promise.all([benchmarkFindings, benchmarkPassedFindings, benchmarkFailedFindings]).then(
      ([benchmarkFindingsResult, benchmarkPassedFindingsResult, benchmarkFailedFindingsResult]) => {
        const totalFindings = benchmarkFindingsResult.body.count;
        const totalPassed = benchmarkPassedFindingsResult.body.count;
        const totalFailed = benchmarkFailedFindingsResult.body.count;
        return {
          name: benchmark,
          postureScore: calculatePostureScore(totalFindings, totalPassed, totalFailed),
          totalFindings,
          totalPassed,
          totalFailed,
        };
      }
    );
  });

  return Promise.all(benchmarkPromises);
```

2021-12-28 07:19 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/server/routes/stats/stats.ts
> +    getResourcesEvaluationEsQuery(cycleId, RULE_FAILED, 5)
Please extract this number to a constant so it'll have a name that explains it

2021-12-28 07:19 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/server/routes/stats/stats.ts
> +  const failedEvaluationPerResorces = failedResourcesGroup.buckets.map((e) => {
Missing `u` in `Resources`

2021-12-28 07:19 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/server/routes/stats/stats.ts
> +  const passedEvaluationPerResorces = passedResourcesGroup.buckets.map((e) => {
Missing `u` in `Resources`

2021-12-28 07:19 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/server/routes/stats/stats.ts
> +        const latestCycleID = await getLatestCycleId(esClient);
These can be ran in parallel

2021-12-28 07:19 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/server/routes/stats/stats.ts
> +        // TODO - validate err object and parse
Please also add a log line here

2021-12-28 09:30 UTC, merged

2021-12-29 09:15 UTC, orouz commented on x-pack/plugins/cloud_security_posture/server/types.ts
> +export interface CspPluginStart {}
@ari-aviran @CohenIdo 

please do not use `eslint-disable` as it disables all lint rules.

only use `disable-next-line` for where it is actually needed

in this case, those interfaces are kinda required for kibana so we do need them even if empty.

2021-12-30 09:04 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/public/pages/compliance_dashboard/compliance_charts/compliance_stats.tsx
> +  const stats = [
Example (partial): You create a `Stats` component (can be better named) and you call it multiple times with the correct property, instead of iterating over an array of its props:

```typescript
<Stats
  title={postureScore}
  description="Posture Score"
  titleColor={getTitleColor(postureScore)}
  iconType={getScoreIcon(postureScore)}
/>
<Stats
  title={'1'}
  description={'Active Frameworks'}
/>
```

And the component itself can be defined like what is rendered inside the `map` method:
```typescript
<EuiFlexItem style={{ height: '45%' }}>
  <EuiPanel hasShadow={false} hasBorder>
    <StyledEuiStat
      title={s.title}
      description={s.description}
      textAlign="left"
      titleColor={s.titleColor}
    >
      {s.renderBody || <EuiIcon type={s.iconType || 'empty'} color={s.titleColor} />}
    </StyledEuiStat>
  </EuiPanel>
</EuiFlexItem>
```

2022-01-05 11:31 UTC, JordanSh commented on x-pack/plugins/cloud_security_posture/public/pages/compliance_dashboard/compliance_charts/compliance_stats.tsx
> +export const ComplianceStats = () => {
for now I'm skipping this since in the Figma designs it seems like it doesn't exist at all. tell me if you think it's worth changing anyway.

2022-01-05 11:32 UTC, JordanSh commented on x-pack/plugins/cloud_security_posture/public/pages/compliance_dashboard/compliance_charts/compliance_stats.tsx
> +  const stats = [
same, skipping for now, will be deprecated soon.

2022-01-05 11:41 UTC, JordanSh commented on x-pack/plugins/cloud_security_posture/public/pages/compliance_dashboard/compliance_charts/score_per_account_chart.tsx
> +      fontFamily: "'Open Sans', Helvetica, Arial, sans-serif",
copy pasted from their euicharts example, at that time we just wanted to have a demo working. this entire file will be deleted for another component based on the Figma designs, I rather skip changes here unless you think its necessary, let me know

2022-01-05 12:20 UTC, JordanSh commented on x-pack/plugins/cloud_security_posture/public/pages/compliance_dashboard/dashboard_sections/benchmarks_section.tsx
> +const logoMap: Record<string, IconType> = {
> since not every string will have an icon type

not sure I understand why. we will map logos to benchmarks names, which are predefined, and all of them should have logos. later when we support custom benchmarks we can decide how to handle that situation.

2022-01-05 12:20 UTC, JordanSh commented on x-pack/plugins/cloud_security_posture/public/pages/compliance_dashboard/dashboard_sections/benchmarks_section.tsx
> +const logoMap: Record<string, IconType> = {
> For safety considering using a method over this map that returns a default icon when the benchmark is of unknown type.

done. thanks!

2022-01-05 15:25 UTC, JordanSh commented on x-pack/plugins/cloud_security_posture/public/components/chart_panel.tsx
> +  <EuiFlexGroup justifyContent="center" alignItems="center" data-test-subj="loading">
not the same case since those prompts are for pages or at least large components, here we are using empty states displays that are coming directly from EuiCharts