Add index mapping
build-security/kibana pull request #49
Opened 2021-12-15 15:09 UTC by CohenIdo

![image](https://user-images.githubusercontent.com/90558359/146211727-4dc1dcb2-5a1f-4138-ab28-c82b6ee3735d.png)

## Summary

Summarize your PR. If it involves visual changes include a screenshot or gif.

### Checklist

Delete any items that are not applicable to this PR.

- [ ] Any text added follows [EUI's writing guidelines](https://elastic.github.io/eui/#/guidelines/writing), uses sentence case text and includes [i18n support](https://github.com/elastic/kibana/blob/main/packages/kbn-i18n/README.md)
- [ ] [Documentation](https://www.elastic.co/guide/en/kibana/master/development-documentation.html) was added for features that require explanation or tutorials
- [ ] [Unit or functional tests](https://www.elastic.co/guide/en/kibana/master/development-tests.html) were updated or added to match the most common scenarios
- [ ] Any UI touched in this PR is usable by keyboard only (learn more about [keyboard accessibility](https://webaim.org/techniques/keyboard/))
- [ ] Any UI touched in this PR does not create any new axe failures (run axe in browser: [FF](https://addons.mozilla.org/en-US/firefox/addon/axe-devtools/), [Chrome](https://chrome.google.com/webstore/detail/axe-web-accessibility-tes/lhdoppojpmngadmnindnejefpokejbdd?hl=en-US))
- [ ] If a plugin configuration key changed, check if it needs to be allowlisted in the cloud and added to the [docker list](https://github.com/elastic/kibana/blob/main/src/dev/build/tasks/os_packages/docker_generator/resources/base/bin/kibana-docker)
- [ ] This renders correctly on smaller devices using a responsive layout. (You can test this [in your browser](https://www.browserstack.com/guide/responsive-testing-on-local-server))
- [ ] This was checked for [cross-browser compatibility](https://www.elastic.co/support/matrix#matrix_browsers)

### Risk Matrix

Delete this section if it is not applicable to this PR.

Before closing this PR, invite QA, stakeholders, and other developers to identify risks that should be tested prior to the change/feature release.

When forming the risk matrix, consider some of the following examples and how they may potentially impact the change:

| Risk                      | Probability | Severity | Mitigation/Notes        |
|---------------------------|-------------|----------|-------------------------|
| Multiple Spaces&mdash;unexpected behavior in non-default Kibana Space. | Low | High | Integration tests will verify that all features are still supported in non-default Kibana Space and when user switches between spaces. |
| Multiple nodes&mdash;Elasticsearch polling might have race conditions when multiple Kibana nodes are polling for the same tasks. | High | Low | Tasks are idempotent, so executing them multiple times will not result in logical error, but will degrade performance. To test for this case we add plenty of unit tests around this logic and document manual testing procedure. |
| Code should gracefully handle cases when feature X or plugin Y are disabled. | Medium | High | Unit tests will verify that any feature flag or plugin combination still results in our service operational. |
| [See more potential risk examples](https://github.com/elastic/kibana/blob/main/RISK_MATRIX.mdx) |

### For maintainers

- [ ] This was checked for breaking API changes and was [labeled appropriately](https://www.elastic.co/guide/en/kibana/master/contributing.html#kibana-release-notes-process)

2021-12-15 15:13 UTC, JordanSh commented on x-pack/plugins/cloud_security_posture/common/constants.ts
> +export const GET_STATS_URL = '/api/csp/stats';
nit but I think `GET` is unneeded. in theory, we might want to send post/put requests here also somewhere down the road. imo `stats_url` is enough

2021-12-15 15:14 UTC, JordanSh commented on x-pack/plugins/cloud_security_posture/public/pages/findings/findings_container.tsx
```suggestion
```

2021-12-15 15:15 UTC, JordanSh commented on x-pack/plugins/cloud_security_posture/server/create_index_template.ts
> +const VERSION = 0.1; // TODO: get current agent version
```suggestion

const VERSION = 0.1; // TODO: get current agent version
```

2021-12-15 15:16 UTC, JordanSh commented on x-pack/plugins/cloud_security_posture/server/create_index_template.ts
> +export async function createIndexTemplate(esClient: ElasticsearchClient) {
nit but `function` is an older syntax. I think 99% of kibana is using the arrow (`() =>`) syntax. your call

2021-12-15 15:21 UTC, JordanSh commented on x-pack/plugins/cloud_security_posture/server/create_index_template.ts
> +  return result;
```suggestion
  try {
    const result = (await esClient.indices.existsIndexTemplate({ name: templateName })).body;
    return result
  } catch (err) {
    throw new Error(`error checking existence of index template: ${err.message}`);
  }
```

maybe I'm missing something but I'm not sure why you need `let` here

2021-12-15 15:23 UTC, JordanSh approved these changes

2021-12-19 08:44 UTC, orouz commented on x-pack/plugins/cloud_security_posture/common/constants.ts
> +export const STATS_URL = '/api/csp/stats';
[URL](https://url.spec.whatwg.org/#api) is the full string (protocol, domain, pathname, query) 

can we rename this to `STATS_PATH` of even better - `STATS_ROUTE_PATH`?

2021-12-19 08:50 UTC, orouz commented on x-pack/plugins/cloud_security_posture/server/create_index_template.ts
> +export const createBackwardsCompatibilityIndexTemplate = (version: number) => {
seems like this fn is only used in this file. 
do we need it to be exported?

2021-12-19 08:50 UTC, orouz commented on x-pack/plugins/cloud_security_posture/server/create_index_template.ts
> +export const doesIndexTemplateExist = async (
seems like this fn is only used in this file.
do we need it to be exported?

2021-12-19 08:53 UTC, orouz commented on x-pack/plugins/cloud_security_posture/server/create_index_template.ts
> +  const backwardsCompatibilityMapping = [indexTemplate]
would be nice if the `indexTemplate` was a function argument (we'd pass the import)
the function itself doesn't sound like it cares about the index itself.

2021-12-19 09:02 UTC, orouz commented on x-pack/plugins/cloud_security_posture/server/create_index_template.ts
> +export const createIndexTemplate = async (esClient: ElasticsearchClient): Promise<void> => {
1. `createIndexTemplate` sounds a bit general. i think this is relevant only for the findings index? (also, the location of the. file in the disk should probably indicate it's relation)

2. a consumer calling `createIndexTemplate` can't tell if the index was created or not after doing `await createIndexTemplate(esClient)`
for example, if `mappings` is falsy, the function just returns implicit undefined, which is the same thing that happens when `mappings` isn't  falsy.

2021-12-19 09:05 UTC, orouz commented on x-pack/plugins/cloud_security_posture/server/plugin.ts
> +    createIndexTemplate(core.elasticsearch.client.asInternalUser);
i think later on we'll want to call `createIndexTemplate` indirectly by initializing some service first.

2021-12-19 09:06 UTC, orouz commented on x-pack/plugins/cloud_security_posture/server/plugin.ts
> +    createIndexTemplate(core.elasticsearch.client.asInternalUser);
also worth adding a comment everywhere we use `asInternalUser` 
smth like
`// TODO: account for user credentials`

2021-12-19 09:15 UTC, orouz commented on x-pack/plugins/cloud_security_posture/server/create_index_template.ts
> +      throw new Error(`error creating index template: ${err.message}`);
i'm not sure this compiles without TS errors? as `err` should be `unknown` which means it doesn't have `message` (from TS perspective)

2021-12-19 09:16 UTC, orouz commented on x-pack/plugins/cloud_security_posture/server/mapping.json
> +{
i would rename this file to indicate what indices are related to this mapping. 
maybe even move it to where it's relevant?

2021-12-19 09:22 UTC, orouz commented on x-pack/plugins/cloud_security_posture/server/create_index_template.ts
> +import { ElasticsearchClient } from 'src/core/server';
```suggestion
import type { ElasticsearchClient } from 'src/core/server';
```

2021-12-19 09:56 UTC, orouz commented on x-pack/plugins/cloud_security_posture/server/create_index_template.ts
> +  const backwardsCompatibilityMapping = [indexTemplate]
also if there's only 1 index mapping and we're providing it, not sure why we need to iterate on it.

2021-12-19 09:58 UTC, orouz commented on x-pack/plugins/cloud_security_posture/server/create_index_template.ts
> +};
instead of throwing and catching again later on, we can just return `false` from the catch block here 

this would simplify the code that calls this function

2021-12-19 10:00 UTC, orouz commented on x-pack/plugins/cloud_security_posture/server/create_index_template.ts
> +};
actually, reading this again - 
if this fn were to throw, it won't be catched at all since it's being called from a `catch` block

2021-12-19 10:01 UTC, orouz commented on x-pack/plugins/cloud_security_posture/server/create_index_template.ts
> +    const existsNow = await doesIndexTemplateExist(esClient, CSP_KUBEBEAT_INDEX_NAME);
this fn may throw, so it needs to be wrapped in another try/catch

but it's probably better to have it always return a boolean

2021-12-19 10:05 UTC, orouz commented on x-pack/plugins/cloud_security_posture/server/create_index_template.ts
> +export const createBackwardsCompatibilityIndexTemplate = (version: number) => {
_nit_

the whole backward compatibility is kinda not clear. 
this function returns `mappings` which has some kind of interface
maybe the fn should be named `get<name of that interface or similar>

2021-12-19 10:08 UTC, orouz commented on x-pack/plugins/cloud_security_posture/server/create_index_template.ts
> +      throw new Error(`error creating index template: ${err.message}`);
if we throw here, it will crash the plugin, as this. fn is called from `plugin.start` 

we should either handle throwing or not throw here at all

2021-12-19 11:51 UTC, orouz commented on x-pack/plugins/cloud_security_posture/server/index_template/create_index_template.test.ts
> +import { elasticsearchClientMock } from 'src/core/server/elasticsearch/client/mocks';
we need to address these lint errors

i think this one can be fixed if we used a relative import  instead (as in - `../../../src` or similar)

(i don't know why access via `tsconfig.rootPath` it's restricted)

2021-12-19 11:52 UTC, orouz commented on x-pack/plugins/cloud_security_posture/server/index_template/create_index_template.test.ts
> +    const response = await createFindingsIndexTemplate(mockEsClient);
is `exists` a string we return or elastic? 

seems like a boolean with be more fitting instead of a string we check for certain value which is essentially the same.

2021-12-19 11:53 UTC, orouz commented on x-pack/plugins/cloud_security_posture/server/index_template/create_index_template.test.ts
> +    const response = await createFindingsIndexTemplate(mockEsClient);
`response` is checked to be a `boolean` here
but same function  `createFindingsIndexTemplate` is supposed to return a string literal - `exists` in the above test. 

why is the return type different?

2021-12-19 11:58 UTC, orouz commented on x-pack/plugins/cloud_security_posture/server/index_template/create_index_template.ts
> +export type Status = true | false | 'exists' | undefined;
1. this type is ambiguous
 - what does `true` mean and how it is different than `exists` ? 
 - what does `undefined` mean and how is it different than `false` ?
2.  the type name is too loose. `Status` is too generic, it needs to be prefixed with something to clarify what it does.

2021-12-19 11:59 UTC, orouz requested changes
see comments

2021-12-19 12:05 UTC, orouz commented
also - 

the jest files needs to applicable for all tests, not just ones from this branch. 

see - https://github.com/build-security/kibana/pull/50

2021-12-19 12:06 UTC, orouz commented on x-pack/plugins/cloud_security_posture/jest.config.ts
> +  ],
this needs to change so other tests match too. 
see https://github.com/build-security/kibana/pull/50 

you can just rebase on top if

2021-12-19 12:10 UTC, orouz commented on x-pack/plugins/cloud_security_posture/server/index_template/create_index_template.ts
> +    if (isExisting === true) return 'exists';
i think it'd be much better if this function would always return a boolean

no need for `exists` string or `undefined`

2021-12-19 12:11 UTC, orouz commented on x-pack/plugins/cloud_security_posture/server/index_template/create_index_template.ts
> +        priority: 500,
what does property mean?

2021-12-19 15:10 UTC, orouz commented on x-pack/plugins/cloud_security_posture/server/plugin.ts
> +    }
i took a quick look and didn't find usages of async `start` 

i think it needs to be a sync function 

for now i would add smth like `createFindingsIndexTemplate().catch(this.logger.error)`
and a `// TODO: error handling`

2021-12-19 15:11 UTC, orouz commented on x-pack/plugins/cloud_security_posture/server/index_template/create_index_template.ts
> +    if (isExisting === true) return true;
_nit_

`if (isExisting) ... `

2021-12-19 15:13 UTC, orouz commented on x-pack/plugins/cloud_security_posture/server/index_template/create_index_template.ts
> +      findingsIndexMapping as Record<string, MappingProperty>
would be nicer if we didn't have to cast here

2021-12-20 09:56 UTC, orouz commented on x-pack/plugins/cloud_security_posture/server/index_template/create_index_template.ts
> +export type Status = boolean;
i would rename `Status` to something less general, like prefixing it with the type of status it is. 

or just use `boolean` instead

2021-12-20 10:02 UTC, orouz approved these changes

2021-12-20 12:52 UTC, merged