Feature 2332/kibana temp ci
build-security/kibana pull request #66
Opened 2021-12-27 21:53 UTC by DaveSys911

## Summary

Summarize your PR. If it involves visual changes include a screenshot or gif.

### Checklist

Delete any items that are not applicable to this PR.

- [ ] Any text added follows [EUI's writing guidelines](https://elastic.github.io/eui/#/guidelines/writing), uses sentence case text and includes [i18n support](https://github.com/elastic/kibana/blob/main/packages/kbn-i18n/README.md)
- [ ] [Documentation](https://www.elastic.co/guide/en/kibana/master/development-documentation.html) was added for features that require explanation or tutorials
- [ ] [Unit or functional tests](https://www.elastic.co/guide/en/kibana/master/development-tests.html) were updated or added to match the most common scenarios
- [ ] Any UI touched in this PR is usable by keyboard only (learn more about [keyboard accessibility](https://webaim.org/techniques/keyboard/))
- [ ] Any UI touched in this PR does not create any new axe failures (run axe in browser: [FF](https://addons.mozilla.org/en-US/firefox/addon/axe-devtools/), [Chrome](https://chrome.google.com/webstore/detail/axe-web-accessibility-tes/lhdoppojpmngadmnindnejefpokejbdd?hl=en-US))
- [ ] If a plugin configuration key changed, check if it needs to be allowlisted in the cloud and added to the [docker list](https://github.com/elastic/kibana/blob/main/src/dev/build/tasks/os_packages/docker_generator/resources/base/bin/kibana-docker)
- [ ] This renders correctly on smaller devices using a responsive layout. (You can test this [in your browser](https://www.browserstack.com/guide/responsive-testing-on-local-server))
- [ ] This was checked for [cross-browser compatibility](https://www.elastic.co/support/matrix#matrix_browsers)

### Risk Matrix

Delete this section if it is not applicable to this PR.

Before closing this PR, invite QA, stakeholders, and other developers to identify risks that should be tested prior to the change/feature release.

When forming the risk matrix, consider some of the following examples and how they may potentially impact the change:

| Risk                      | Probability | Severity | Mitigation/Notes        |
|---------------------------|-------------|----------|-------------------------|
| Multiple Spaces&mdash;unexpected behavior in non-default Kibana Space. | Low | High | Integration tests will verify that all features are still supported in non-default Kibana Space and when user switches between spaces. |
| Multiple nodes&mdash;Elasticsearch polling might have race conditions when multiple Kibana nodes are polling for the same tasks. | High | Low | Tasks are idempotent, so executing them multiple times will not result in logical error, but will degrade performance. To test for this case we add plenty of unit tests around this logic and document manual testing procedure. |
| Code should gracefully handle cases when feature X or plugin Y are disabled. | Medium | High | Unit tests will verify that any feature flag or plugin combination still results in our service operational. |
| [See more potential risk examples](https://github.com/elastic/kibana/blob/main/RISK_MATRIX.mdx) |

### For maintainers

- [ ] This was checked for breaking API changes and was [labeled appropriately](https://www.elastic.co/guide/en/kibana/master/contributing.html#kibana-release-notes-process)

2021-12-30 08:34 UTC, ari-aviran requested changes
We should add TypeScript compilation, linting and testing of our package, @orouz please provide the details (commands) on how to do so

2021-12-30 08:34 UTC, ari-aviran commented on package.json
> +//  Todo optimise build command & delete before merge to elastic/kibana
You can't add comments in JSON, it also fails the build

2021-12-30 08:34 UTC, ari-aviran commented on packages/kbn-pm/src/commands/bootstrap.ts
> +      // ['scripts/build_ts_refs', '--ignore-type-failures', '--no-cache'],
Remove if not used, we should probably not touch this file (other than debugging)

2021-12-30 08:34 UTC, ari-aviran commented on .github/workflows/automerge.yml
> +name: automerge
I'm hesitant to add auto merging, @orouz what do you think?

2021-12-30 11:25 UTC, DaveSys911 commented on package.json
> +//  Todo optimise build command & delete before merge to elastic/kibana
@ari-aviran had a cognitive slip due to the late hour doing this, removed.

2021-12-30 11:34 UTC, DaveSys911 commented on .github/workflows/automerge.yml
> +name: automerge
@ari-aviran I understand your concerns. So this isn't exactly "auto".  It's something made by @kfirpeled which we used at build.sec .

 Basically, once you open a pr(draft excluded) and submit it for review.
You can choose to label the pr. It will auto-update from main, and only if the mandatory checks are passed and review approved it will auto-merge.

This comes to compensate for the currently long ci runs (40 mins atm - discussed with kfir to open a task to optimize depending on our readiness to merge),  to free up the dev from waiting for ci or having to check the status(maybe consider some slack/gh push for the pr owner if ci fails)

This requires the team to follow a simple guideline. Not to label and approve WIP PRS. For example hit the approve button on a labeled pr and comment " Approved, but do x,y,z".

This is 100% for your convenience @orouz @JordanSh @CohenIdo , so let me know.

2022-01-03 08:34 UTC, kfirpeled commented on .github/workflows/automerge.yml
> +name: automerge
Lets first check in the kibana channel to see their thoughts on this
Better to have a separate ticket on this one so we will prioritize that in the backlog

2022-01-03 15:10 UTC, DaveSys911 commented on .github/workflows/automerge.yml
> +name: automerge
@kfirpeled it's temp ci meant for us until we merge to upstream

2022-11-21 11:27 UTC, closed without merging