add sort for finding end point + API test
build-security/kibana pull request #68
Opened 2021-12-28 14:53 UTC by CohenIdo

- add sorting to findings endpoint 
- add API testing

2021-12-28 14:57 UTC, CohenIdo commented on x-pack/plugins/cloud_security_posture/server/routes/findings/findings.test.ts
>   * 2.0; you may not use this file except in compliance with the Elastic License
This page existed but all the content move to `get_latest_cycle.test.ts`.
So actually `get_latest_cycle.test.ts` does not contain any new code, and the `findings.test.ts` below is all new code.
For some reason, git didn't recognize it.

2021-12-30 08:14 UTC, ari-aviran requested changes
This branch has many TS errors, please fix them first as I can not even run the tests

2022-01-04 08:21 UTC, kfirpeled requested changes

2022-01-04 08:21 UTC, kfirpeled commented on x-pack/plugins/cloud_security_posture/server/routes/findings/findings.ts
> +    queryParams.page <= 1 ? 0 : queryParams.page * queryParams.per_page - queryParams.per_page + 1,
maybe translate is a better wording?

2022-01-04 08:21 UTC, kfirpeled commented on x-pack/plugins/cloud_security_posture/server/routes/findings/findings.ts
> +      path: FINDINGS_ROUTE_PATH,
need to check if thers a guidline

2022-01-04 08:21 UTC, kfirpeled commented on x-pack/plugins/cloud_security_posture/server/routes/findings/findings.ts
> +  esClient: ElasticsearchClient
lets improve

2022-01-04 15:44 UTC, orouz commented on x-pack/plugins/cloud_security_posture/server/routes/findings/findings.test.ts
> +  it('test getting speific fields from findings index', async () => {
note that `src/core/server/saved_objects/routes/integration_tests/find.test.ts` is a core plugin and the things they test there should probably not be tested again. (not the structure)

2022-01-04 15:47 UTC, orouz commented on x-pack/plugins/cloud_security_posture/server/routes/findings/findings.ts
> +      path: FINDINGS_ROUTE_PATH,
> it should be `FINDINGS_ROUTE_PATH + '_find'` this will allow us to add more capabilities to the findings route

can you elaborate? not sure i follow how it will change what we choose return

2022-01-18 18:17 UTC, kfirpeled requested changes
maybe it would be good to add some integration tests as well?
since you are building the query manually it is worth seeing it passes es and returned as expected. wdyt?

2022-01-18 18:17 UTC, kfirpeled commented on x-pack/plugins/cloud_security_posture/server/routes/findings/findings.ts
> +const getSearchFields = (fields: string | undefined) => (fields ? { _source: [fields] } : {});
fields is of type `string[]` no?

2022-01-18 18:17 UTC, kfirpeled commented on x-pack/plugins/cloud_security_posture/server/routes/findings/findings.ts
> +import type { SortOrder } from '@elastic/elasticsearch/lib/api/types';
more general suggestion - in some places I saw the `findingsInputSchema` rt object is well documented
wdyt we will do something similar? see examples: `CasesFindRequestRt`, `SubCasesFindRequestRt`,

2022-01-20 14:28 UTC, kfirpeled commented on x-pack/plugins/cloud_security_posture/server/routes/findings/findings.test.ts
> +                      hits: [{ fields: { 'run_id.keyword': ['randomId1'] } }],
Actually @ari-aviran shared with us some useful examples of it
It is not something that is critical in this case. just to share with you some other approaches

2022-01-20 14:37 UTC, kfirpeled commented on x-pack/plugins/cloud_security_posture/server/routes/findings/findings.test.ts
> +      expect(mockEsClient.search.mock.calls).toHaveLength(2);
a more human readable approach could be
`expect(mockEsClient.search).toHaveBeenCalledTimes(2)`

2022-01-20 14:37 UTC, kfirpeled commented on x-pack/plugins/cloud_security_posture/server/routes/findings/findings.test.ts
> +      const handlerArgs = mockEsClient.search.mock.calls[0][0];
So that can be done with `toHaveBeenCalledTimes(1)`
It is just a suggestion
I think human readable code in tests that are referring your attentions without to much assumptions makes the code present what was your intent
without reading any line of documentation

2022-01-20 14:37 UTC, kfirpeled commented on x-pack/plugins/cloud_security_posture/server/routes/findings/findings.ts
> +import type { SortOrder } from '@elastic/elasticsearch/lib/api/types';
for sure. but no point on waiting with it imo

2022-01-20 14:37 UTC, kfirpeled commented on x-pack/plugins/cloud_security_posture/server/routes/findings/findings.ts
> +      path: FINDINGS_ROUTE_PATH,
actually it doesn't really critical.
there's no consolidation regarding rest paths on kibana for that use-case that i saw

2022-01-24 13:27 UTC, CohenIdo commented on x-pack/plugins/cloud_security_posture/server/routes/findings/get_latest_cycle.test.ts
> +  it('expect to find empty bucket', async () => {
Actualy it will return empty response only if the client is not initialize. 
It cannot happen in our case cause elasticsearch client is initialize when we start the plugin. 
I droped the other test.

2022-01-24 13:27 UTC, CohenIdo commented on x-pack/plugins/cloud_security_posture/server/routes/findings/findings.ts
> +import type { SortOrder } from '@elastic/elasticsearch/lib/api/types';
add documentation at the bottom of the page.

2022-01-24 20:12 UTC, kfirpeled submitted a review, later dismissed

2022-01-24 20:12 UTC, kfirpeled commented on x-pack/plugins/cloud_security_posture/server/routes/findings/findings.ts
> +   * Boolean flag to indicate for receive inly the latest findings
fix typos `Boolean flag to indicate for receiving only the latest findings`

2022-01-24 20:12 UTC, kfirpeled commented on x-pack/plugins/cloud_security_posture/server/routes/findings/get_latest_cycle.test.ts
> +    logger = loggingSystemMock.createLogger();
merge the two `beforeEach` clauses into one

2022-01-24 20:21 UTC, CohenIdo commented on x-pack/plugins/cloud_security_posture/server/routes/findings/findings.ts
> +   * Boolean flag to indicate for receive inly the latest findings
done

2022-01-24 20:21 UTC, CohenIdo commented on x-pack/plugins/cloud_security_posture/server/routes/findings/get_latest_cycle.test.ts
> +    logger = loggingSystemMock.createLogger();
done:)

2022-01-24 21:00 UTC, orouz commented on x-pack/plugins/cloud_security_posture/server/routes/findings/findings.test.ts
> +  describe('test input schema', () => {
i don't think we need to test the schema at all?

see example with positive integer

2022-01-24 21:00 UTC, orouz commented on x-pack/plugins/cloud_security_posture/server/routes/findings/findings.test.ts
> +    });
i think this is (as in - making sure the schema validates correctly) is covered?

for example, the second test at `packages/kbn-config-schema/src/types/number_type.test.ts` in `describe#min` tests that the validator throws when given a value larger than min, which seems like this case, but same is true for all other schema tests too.

2022-01-25 09:52 UTC, kfirpeled approved these changes
lgtm

2022-01-25 10:01 UTC, merged