Findings i18n
build-security/kibana pull request #74
Opened 2021-12-29 14:30 UTC by orouz

2021-12-29 14:48 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/pages/findings/constants.ts
> +});
this is an example of a translation

i used upper case as it's a constant (has the type `string`) 

so `Findings` would be the component and `FINDINGS` would be the text

figured it's nicer than adding `_TEXT` to each variable. 

we should have a convention for how we handle this. seems like in kibana some do like this some do camelCase.

2021-12-29 14:49 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/pages/findings/findings_flyout.tsx
> +import * as TX from './constants';
`TX` as in text

suggestions are obviously welcome

2021-12-30 08:37 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/public/pages/findings/constants.ts
> +});
I like using `SCREAMING_SNAKE_CASE` as these are indeed constants, no need for the `_TEXT` suffix

2021-12-30 08:43 UTC, ari-aviran requested changes

2021-12-30 08:43 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/public/pages/findings/constants.ts
> +export const NAME = i18n.translate('xpack.csp.name', {
Lets move all the text to a file of its own called "text", "copy" or "translations" (I prefer the first two or something in that spirit, as "translations" imply they'll have actual translations to different languages in them). This way the imports will be clear

2021-12-30 08:43 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/public/pages/findings/findings.test.tsx
> +import { MISSING_KUBEBEAT } from '../../common/translations';
This is the wrong import

2021-12-30 08:43 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/public/pages/findings/findings_flyout.tsx
> +import * as TX from './constants';
I think we can spare two more letters to make it `TEXT` :)

2021-12-30 08:43 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/public/pages/findings/findings_flyout.tsx
> +import * as TX from './constants';
This import is problematic since it also brings along non-textual constants. See my other comment regarding splitting the textual constants to a different file

2021-12-30 08:43 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/public/pages/findings/constants.ts
> +export const RULE_NAME = i18n.translate('xpack.csp.rule_name', {
The naming scheme is a little simplistic here, this constant for example is used as a column header and is cased appropriately in title case (`Rule Name` as opposed to `Rule name` or `rule name`). I think we should add some more info on most of the constants in the name, this can be `RULE_NAME_HEADER` or `RULE_NAME_COLUMN_HEADER` for example

2022-01-03 10:02 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/pages/findings/constants.ts
> +export const NAME = i18n.translate('xpack.csp.name', {
1. note that this file includes both `TEST_SUBJECTS` and `translations` as they are both a `string` constant, renaming to `translations` isn't entirely correct here. maybe multiple files? 
2. `translations/constants` seems like the convention in kibana. didn't see a `texts/copy` file, although i think `text` is legit.

2022-01-03 10:05 UTC, orouz commented
> I think we can spare two more letters to make it TEXT :)

2 chars for the rename, then 2 chars for each one of the `82` consumers

maybe keep as is or rename to something shorter?

2022-01-03 10:11 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/pages/findings/constants.ts
> +export const RULE_NAME = i18n.translate('xpack.csp.rule_name', {
changed, not quite sure about this tho

2022-01-03 10:17 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/pages/findings/findings_flyout.tsx
> +import * as TX from './constants';
haven't checked but i i'd be surprised if it wasn't tree shaked

2022-01-03 10:35 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/public/pages/findings/constants.ts
> +export const NAME = i18n.translate('xpack.csp.name', {
Lets do a separate file under `translations/constants` then

2022-01-03 10:37 UTC, ari-aviran commented
> > I think we can spare two more letters to make it TEXT :)
> 
> 2 chars for the rename, then 2 chars for each one of the `82` consumers
> 
> maybe keep as is or rename to something shorter?
> 
> @ari-aviran

Not super-important, I think we should got with `TEXT` for clarity over brevity, but up to you

2022-01-04 16:36 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/pages/findings/findings_flyout.tsx
> +import * as TX from './constants';
fixed

2022-01-05 08:52 UTC, ari-aviran approved these changes
Please try and avoid force-pushing in the future as it makes it hard to keep track of review history

2022-01-05 09:00 UTC, orouz commented
@ari-aviran 

> Please try and avoid force-pushing in the future as it makes it hard to keep track of review history

when working with `rebase` we must force push

this is also in [kibana git guide ](https://www.elastic.co/guide/en/kibana/7.16/development-github.html#:~:text=git%20push%20origin%20name%2Dof%2Dyour%2Dbranch%20%2D%2Dforce)

2022-01-05 09:41 UTC, merged