Fix internal navigation with query
build-security/kibana pull request #89
Opened 2022-01-05 18:11 UTC by orouz

fixes:
- [Re-use constant](https://github.com/build-security/kibana/pull/43#discussion_r773819913)
- [`.filter` logic](https://github.com/build-security/kibana/pull/43#discussion_r773823912)

from:
- https://github.com/elastic/security-team/issues/2582

2022-01-06 08:53 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/pages/compliance_dashboard/compliance_charts/resources_at_risk_chart.tsx
> +  query: `resource.filename : "${resource}" and result.evaluation : "${evaluation}" `,
i'd rather build the query using `@kbn/es-query` but that didn't work out yet

2022-01-06 14:42 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/pages/compliance_dashboard/compliance_charts/resources_at_risk_chart.tsx
> +    navigate(allNavigationItems.findings.id, getResourceQuery(resource, evaluation));
navigating by a known page `id` 
later on we can type the query too. (security solution does something similar)

2022-01-10 13:03 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/pages/compliance_dashboard/compliance_charts/resources_at_risk_chart.tsx
>    };
main change is to use react-router's hooks and expose functions to encode/decode the query param.

2022-01-10 13:16 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/pages/compliance_dashboard/compliance_charts/resources_at_risk_chart.tsx
> +  query: `resource.filename : "${resource}" and result.evaluation : "${evaluation}" `,
btw this changed because the consolidation that was made between pages that navigate with query is that both use an object to pass their query, not a string.

2022-01-13 09:46 UTC, ari-aviran requested changes

2022-01-13 09:46 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/public/common/navigation/constants.ts
> +export type CspNavigationItemsMap = { [Page in Routes[number] as Page['id']]: Page };
No need to export this

2022-01-13 09:46 UTC, ari-aviran commented on x-pack/plugins/cloud_security_posture/public/common/navigation/constants.ts
> +const createRoutes = <T extends readonly CspNavigationItem[]>(v: T) => v;
This can be enhanced to create the final `allNavigationItems` without all the intermediate types/constants:

```typescript
const createRoutes = <T extends readonly CspNavigationItem[], K extends T[number]['id']>(
  routes: T
): Record<K, T[number]> => Object.fromEntries(routes.map((v) => [v.id, v])) as Record<K, T[number]>;

export const allNavigationItems = createRoutes([
  { name: TEXT.DASHBOARD, path: '/dashboard', id: 'dashboard' },
  { name: TEXT.FINDINGS, path: '/findings', id: 'findings' },
] as const);
```

<img width="920" alt="image" src="https://user-images.githubusercontent.com/94899776/149305818-21d31073-08a4-4891-9362-45ca8f2feb5f.png">

2022-01-13 09:54 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/common/navigation/constants.ts
> +const createRoutes = <T extends readonly CspNavigationItem[]>(v: T) => v;
these aren't the same. 

note how in your type the keys are a union and so are the values, which isn't correct, as opposed to having each key with its own value:


![Screen Shot 2022-01-13 at 11 50 46](https://user-images.githubusercontent.com/20814186/149306946-2a2d971a-3f52-47eb-9732-93d91a09b6f1.png)

2022-01-13 09:58 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/common/navigation/constants.ts
> +const createRoutes = <T extends readonly CspNavigationItem[]>(v: T) => v;
this illustrates the problem better:
![Screen Shot 2022-01-13 at 11 57 32](https://user-images.githubusercontent.com/20814186/149308118-581ebc47-773e-4205-9492-75a239330dc0.png)

2022-01-13 10:06 UTC, orouz commented on x-pack/plugins/cloud_security_posture/public/common/navigation/constants.ts
> +const createRoutes = <T extends readonly CspNavigationItem[]>(v: T) => v;
but we can simplify to this: 

```
const createRoutes = <T extends readonly CspNavigationItem[]>(v: T) =>
  Object.fromEntries(v.map((v) => [v.id, v])) as { [Page in T[number] as Page['id']]: Page };

```

which cuts the intermediate types

2022-01-13 10:15 UTC, ari-aviran approved these changes

2022-01-13 10:16 UTC, merged