add logger and logs
build-security/kibana pull request #91
Opened 2022-01-10 08:44 UTC by CohenIdo

add logger to APIs

2022-01-13 14:47 UTC, kfirpeled requested changes

2022-01-13 14:47 UTC, kfirpeled commented on x-pack/plugins/cloud_security_posture/server/index_template/create_index_template.test.ts
> +  const logger: ReturnType<typeof loggingSystemMock.createLogger> =
looking on other examples, the initialization of the mock is happening in the `beforeeach` step
I think it is a good practice
wdyt?

2022-01-13 14:47 UTC, kfirpeled commented on x-pack/plugins/cloud_security_posture/server/index_template/create_index_template.ts
> +    logger.error(`Invalid usage in putIndexTemplate for index ${indexName}`);
please log the `err` as well

better text for the log is
`Failed to create index pattern ${indexName}, err`

2022-01-13 14:47 UTC, kfirpeled commented on x-pack/plugins/cloud_security_posture/server/index_template/create_index_template.ts
> +    logger.error(`Invalid usage in putIndexTemplate for index ${indexName}`);
I saw now this text is already used
So maybe `putIndexTemplate failed`

2022-01-13 14:47 UTC, kfirpeled commented on x-pack/plugins/cloud_security_posture/server/index_template/create_index_template.ts
> +    logger.error(`Invalid usage in putIndexTemplate for index ${indexName}`);
btw, I see todo:fix types.
what about it?

2022-01-13 14:47 UTC, kfirpeled commented on x-pack/plugins/cloud_security_posture/server/index_template/create_index_template.ts
> +    logger.error(`Failed to create index template ${CSP_FINDINGS_INDEX_NAME}`);
log the `err` as well

2022-01-13 14:47 UTC, kfirpeled commented on x-pack/plugins/cloud_security_posture/server/routes/stats/stats.ts
> +  if (lastCycle?._source?.run_id === undefined) {
how does it relates to this pr?

2022-01-13 14:47 UTC, kfirpeled commented on x-pack/plugins/cloud_security_posture/server/routes/stats/stats.ts
> +  if (benchmarksBuckets?.buckets === undefined) {
related to this pr?

2022-01-17 16:16 UTC, CohenIdo commented on x-pack/plugins/cloud_security_posture/server/index_template/create_index_template.ts
> +    logger.error(`Invalid usage in putIndexTemplate for index ${indexName}`);
A variable that defines under `beforeEach` is not available for the test. 
`beforeEach` contains mainly methods that we want o do before each test, in this case, the logger is used inside the test itself.

2022-01-17 16:20 UTC, CohenIdo commented on x-pack/plugins/cloud_security_posture/server/routes/stats/stats.ts
> +  if (benchmarksBuckets?.buckets === undefined) {
Same one^

2022-01-17 16:20 UTC, CohenIdo commented on x-pack/plugins/cloud_security_posture/server/index_template/create_index_template.test.ts
> +  const logger: ReturnType<typeof loggingSystemMock.createLogger> =
A variable that defines under beforeEach is not available for the test.
beforeEach contains mainly methods that we want o do before each test, in this case, the logger is used inside the test itself.

2022-01-17 16:23 UTC, CohenIdo commented on x-pack/plugins/cloud_security_posture/server/index_template/create_index_template.ts
> +    logger.error(`Invalid usage in putIndexTemplate for index ${indexName}`);
Done:)

2022-01-17 16:28 UTC, CohenIdo commented on x-pack/plugins/cloud_security_posture/server/index_template/create_index_template.test.ts
> +  const logger: ReturnType<typeof loggingSystemMock.createLogger> =
If I move the logger initialization to `beforeEach` I would also move the usage of the logger to `beforeEach` and I am afraid is not our use case.  
In `task_manager` plugin they are doing the same -> `x-pack/plugins/task_manager/server/monitoring/capacity_estimation.test.ts`
Another alternative that I saw is to define them inside the test itself.

2022-01-18 18:33 UTC, kfirpeled commented on x-pack/plugins/cloud_security_posture/server/index_template/create_index_template.ts
> +    logger.error(`Failed to create index template ${CSP_FINDINGS_INDEX_NAME}, ${err}`);
from a look in the kibana code it seems the common usage is
```js
logger.error('error message here')
logger.error(err)
```

2022-01-18 18:33 UTC, kfirpeled commented on x-pack/plugins/cloud_security_posture/server/index_template/create_index_template.ts
> +    logger.error(`Failed to create index template ${CSP_FINDINGS_INDEX_NAME}, ${err}`);
and worth adding debug log message whenever you are about to create something

2022-01-18 18:33 UTC, kfirpeled commented on x-pack/plugins/cloud_security_posture/server/index_template/create_index_template.test.ts
> +  const logger: ReturnType<typeof loggingSystemMock.createLogger> =
attaching example

```js
describe('configureClient', () => {
  let logger: ReturnType<typeof loggingSystemMock.createLogger>;
  let config: ElasticsearchClientConfig;

  beforeEach(() => {
    logger = loggingSystemMock.createLogger();
    config = createFakeConfig();
    parseClientOptionsMock.mockReturnValue({});
    ClientMock.mockImplementation(() => createFakeClient());
  });
```

the logger is available this way for the tests

2022-01-18 18:33 UTC, kfirpeled commented on x-pack/plugins/cloud_security_posture/server/plugin.ts
> +    // Register server side APIs
add line of space before a comment

2022-01-18 18:33 UTC, kfirpeled commented on x-pack/plugins/cloud_security_posture/server/routes/index.ts
> +export function defineRoutes(router: IRouter, logger: Logger) {
example i saw today:

```js
export interface RouteDefinitionParams {
  readonly router: IRouter;
  readonly logger: Logger;
}

export function defineRoutes(params: RouteDefinitionsParams) {
  defineGetStatsRoute(params);
  defineGetFindingsIndexRoute(params);
```

2022-01-18 18:33 UTC, kfirpeled commented on x-pack/plugins/cloud_security_posture/server/routes/index.ts
> +export function defineRoutes(router: IRouter, logger: Logger) {
this way adding a new parameter doesn't require to refactor all signatures

2022-01-18 18:33 UTC, kfirpeled commented on x-pack/plugins/cloud_security_posture/server/routes/stats/stats.ts
> +  if (lastCycle?._source?.run_id === undefined) {
no need, just out of curiosity

2022-01-18 18:33 UTC, kfirpeled commented on x-pack/plugins/cloud_security_posture/server/index_template/create_index_template.ts
> +    logger.error(`Failed to create index template ${CSP_FINDINGS_INDEX_NAME}, ${err}`);
(sorry for the confusion before)

2022-01-19 07:09 UTC, CohenIdo commented on x-pack/plugins/cloud_security_posture/server/index_template/create_index_template.ts
> +    logger.error(`Failed to create index template ${CSP_FINDINGS_INDEX_NAME}, ${err}`);
Done:)

2022-01-19 07:19 UTC, CohenIdo commented on x-pack/plugins/cloud_security_posture/server/routes/index.ts
> +export function defineRoutes(router: IRouter, logger: Logger) {
You're right, I want to talk with you about this issue.
Is not just the logger, also when we inject other plugins to our plugin and want to enrich `router.context` we can do it with a similar approach (but there is some more approaches in different plugins).
It's required to change the plugin setup and I would like to do it in a different task after merging the benchmark PR as well.

2022-01-19 07:36 UTC, CohenIdo commented
The CI is failing due to TS error that was fixed in this [PR](https://github.com/build-security/kibana/pull/102). (Still not merged)

2022-01-19 10:24 UTC, kfirpeled submitted a review, later dismissed

2022-01-20 14:20 UTC, kfirpeled approved these changes

2022-01-20 14:31 UTC, merged